const K={products:'dah_products_v2',sales:'dah_sales_v2',purchases:'dah_purchases_v2',suppliers:'dah_suppliers_v2',expenses:'dah_expenses_v2'};
let products=load('products'),sales=load('sales'),purchases=load('purchases'),suppliers=load('suppliers'),expenses=load('expenses'),cart=[];
function load(k){try{return JSON.parse(localStorage.getItem(K[k])||'[]')}catch{return[]}} function save(){for(const k of Object.keys(K))localStorage.setItem(K[k],JSON.stringify({products,sales,purchases,suppliers,expenses}[k]||[]))} function money(n){return Number(n||0).toLocaleString('fr-DZ')+' دج'} function esc(x){return String(x??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
const seed=[['100000000001','أرز أبيض','Riz blanc','مواد غذائية'],['100000000002','أرز بسمتي','Riz basmati','مواد غذائية'],['100000000003','كسكس متوسط','Couscous moyen','مواد غذائية'],['100000000004','سميد متوسط','Semoule moyenne','مواد غذائية'],['100000000005','فرينة','Farine','مواد غذائية'],['100000000006','سكر أبيض','Sucre blanc','مواد غذائية'],['100000000007','ملح','Sel','مواد غذائية'],['100000000008','زيت مائدة','Huile de table','مواد غذائية'],['100000000009','قهوة','Café','مشروبات'],['100000000010','شاي','Thé','مشروبات'],['100000000011','عدس','Lentilles','بقوليات'],['100000000012','حمص','Pois chiches','بقوليات'],['100000000013','فاصوليا بيضاء','Haricots blancs','بقوليات'],['100000000014','مقرونة سباغيتي','Spaghetti','مقرونة'],['100000000015','مقرونة قصيرة','Pâtes courtes','مقرونة'],['100000000016','طماطم مصبرة','Tomate concentrée','معلبات'],['100000000017','هريسة','Harissa','صلصات'],['100000000018','مايونيز','Mayonnaise','صلصات'],['100000000019','كاتشب','Ketchup','صلصات'],['100000000020','مربى الفراولة','Confiture de fraise','فطور']]; for(let i=21;i<=200;i++)seed.push([String(100000000000+i),`منتج ${i}`,`Produit ${i}`,'متنوع']);
function showPage(id,btn){document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));document.getElementById(id).classList.add('active');document.querySelectorAll('nav button').forEach(x=>x.classList.remove('active'));if(btn)btn.classList.add('active');renderAll()}
function addProduct(){const p={id:Date.now(),barcode:pBarcode.value.trim(),ar:pAr.value.trim(),fr:pFr.value.trim(),cat:pCat.value.trim()||'متنوع',buy:+pBuy.value||0,sell:+pSell.value||0,qty:+pQty.value||0,min:+pMin.value||2};if(!p.ar&&!p.fr)return alert('اكتب اسم المنتج');products.push(p);save();['pBarcode','pAr','pFr','pCat','pBuy','pSell','pQty'].forEach(id=>document.getElementById(id).value='');renderAll()}
function load200(){let added=0;seed.forEach(s=>{if(!products.some(p=>p.barcode===s[0])){products.push({id:Date.now()+added,barcode:s[0],ar:s[1],fr:s[2],cat:s[3],buy:0,sell:0,qty:0,min:2});added++}});save();alert(`تم تحميل ${added} منتج جديد. المجموع ${products.length}.`);renderAll()}
function renderProducts(){const q=(productSearch.value||'').toLowerCase();productsBody.innerHTML=products.filter(p=>(p.ar+' '+p.fr+' '+p.barcode).toLowerCase().includes(q)).map(p=>`<tr class="${p.qty<=p.min?'low':''}"><td>${esc(p.barcode)||'-'}</td><td>${esc(p.ar)}<br><small>${esc(p.fr)}</small></td><td>${esc(p.cat)}</td><td>${money(p.buy)}</td><td>${money(p.sell)}</td><td>${p.qty}</td><td><button class="btn secondary" onclick="editProduct(${p.id})">تعديل</button></td></tr>`).join('')}
function editProduct(id){const p=products.find(x=>x.id===id);if(!p)return;const q=prompt('الكمية الجديدة',p.qty);if(q!==null)p.qty=Math.max(0,+q||0);const sell=prompt('سعر البيع',p.sell);if(sell!==null)p.sell=Math.max(0,+sell||0);const buy=prompt('سعر الشراء',p.buy);if(buy!==null)p.buy=Math.max(0,+buy||0);save();renderAll()}
function findProduct(q){q=(q||'').trim().toLowerCase();return products.find(p=>(p.barcode||'').toLowerCase()===q)||products.find(p=>(p.ar+' '+p.fr).toLowerCase().includes(q))}
function addSaleBySearch(){const p=findProduct(saleSearch.value);if(!p)return alert('المنتج غير موجود');if(p.qty<=0)return alert('المخزون منتهٍ');const c=cart.find(x=>x.id===p.id);if(c)c.qty++;else cart.push({id:p.id,name:p.ar||p.fr,price:+p.sell||0,qty:1,buy:+p.buy||0});saleSearch.value='';renderCart()}
function renderCart(){cartBody.innerHTML=cart.map((c,i)=>`<tr><td>${esc(c.name)}</td><td>${money(c.price)}</td><td><input type="number" min="1" max="99" value="${c.qty}" onchange="cart[${i}].qty=Math.max(1,+this.value||1);renderCart()"></td><td>${money(c.price*c.qty)}</td><td><button class="btn danger" onclick="cart.splice(${i},1);renderCart()">×</button></td></tr>`).join('');cartTotal.textContent=cart.reduce((a,c)=>a+c.price*c.qty,0).toLocaleString('fr-DZ')}
function clearCart(){cart=[];renderCart()} function finishSale(){if(!cart.length)return alert('السلة فارغة');for(const c of cart){const p=products.find(x=>x.id===c.id);if(!p||p.qty<c.qty)return alert('الكمية غير متوفرة: '+c.name)}const total=cart.reduce((a,c)=>a+c.price*c.qty,0);sales.push({id:Date.now(),date:new Date().toISOString(),items:cart.map(x=>({...x})),total});cart.forEach(c=>products.find(x=>x.id===c.id).qty-=c.qty);save();alert('تم تسجيل البيع: '+money(total));clearCart();renderAll()}
function scanLookup(){const p=findProduct(scanInput.value);scanResult.innerHTML=p?`<div class="card"><h3>${esc(p.ar)}</h3><p>${esc(p.fr)}</p><p>Barcode: <b>${esc(p.barcode)}</b></p><p>الشراء: <b>${money(p.buy)}</b> — البيع: <b>${money(p.sell)}</b> — المخزون: <b>${p.qty}</b></p></div>`:'<div class="card dangerText">لم يتم العثور على المنتج.</div>'} function startPhotoScan(){photoScan.click()} async function detectPhoto(input){const f=input.files&&input.files[0];if(!f)return;if(!('BarcodeDetector' in window))return alert('التصوير التلقائي غير مدعوم في هذا الجهاز. استعمل قارئ USB أو أدخل الكود يدوياً.');try{const b=new BarcodeDetector({formats:['ean_13','ean_8','upc_a','upc_e','code_128','code_39','itf']});const bmp=await createImageBitmap(f);const r=await b.detect(bmp);if(!r.length)return alert('لم يتم العثور على باركود واضح.');scanInput.value=r[0].rawValue;scanLookup()}catch(e){alert('تعذر قراءة الصورة.')}}
function addPurchase(){let q=Math.max(1,+buyQty.value||0),cost=Math.max(0,+buyCost.value||0),name=buyProduct.value.trim(),barcode=buyBarcode.value.trim(),p=findProduct(barcode||name);if(!p){if(!name)return alert('اكتب اسم المنتج');p={id:Date.now(),barcode,ar:name,fr:'',cat:'متنوع',buy:cost,sell:0,qty:0,min:2};products.push(p)}p.qty+=q;p.buy=cost||p.buy;purchases.unshift({id:Date.now(),date:new Date().toISOString(),product:p.ar,barcode:p.barcode,qty:q,cost, supplier:buySupplier.value.trim()});save();['buyBarcode','buyProduct','buyQty','buyCost','buySupplier'].forEach(id=>document.getElementById(id).value='');renderAll()}
function renderPurchases(){purchasesBody.innerHTML=purchases.slice(0,100).map(x=>`<tr><td>${new Date(x.date).toLocaleDateString('fr-DZ')}</td><td>${esc(x.product)}</td><td>${x.qty}</td><td>${money(x.cost*x.qty)}</td><td>${esc(x.supplier)}</td></tr>`).join('')}
function addSupplier(){const n=sName.value.trim();if(!n)return alert('اكتب اسم المورد');suppliers.push({id:Date.now(),name:n,phone:sPhone.value.trim(),address:sAddress.value.trim(),note:sNote.value.trim()});save();['sName','sPhone','sAddress','sNote'].forEach(id=>document.getElementById(id).value='');renderAll()} function renderSuppliers(){suppliersBody.innerHTML=suppliers.map(x=>`<tr><td>${esc(x.name)}</td><td>${esc(x.phone)}</td><td>${esc(x.address)}</td><td>${esc(x.note)}</td></tr>`).join('')}
function addExpense(){const label=eLabel.value.trim(),amount=Math.max(0,+eAmount.value||0);if(!label||!amount)return alert('أدخل نوع المصروف والمبلغ');expenses.unshift({id:Date.now(),date:eDate.value||new Date().toISOString().slice(0,10),label,amount,note:eNote.value.trim()});save();['eLabel','eAmount','eNote'].forEach(id=>document.getElementById(id).value='');renderAll()} function renderExpenses(){expensesBody.innerHTML=expenses.slice(0,100).map(x=>`<tr><td>${x.date}</td><td>${esc(x.label)}</td><td>${money(x.amount)}</td><td>${esc(x.note)}</td></tr>`).join('')}
function daySales(){const d=new Date().toISOString().slice(0,10);return sales.filter(s=>s.date.slice(0,10)===d)} function monthSales(){const d=new Date(),m=d.toISOString().slice(0,7);return sales.filter(s=>s.date.slice(0,7)===m)} function reportToday(){const a=daySales(),t=a.reduce((x,s)=>x+s.total,0),ex=expenses.filter(e=>e.date===new Date().toISOString().slice(0,10)).reduce((x,e)=>x+e.amount,0);reportBox.innerHTML=`<div class="kpi">${money(t)}</div><p>عدد الفواتير: ${a.length}</p><p>مصاريف اليوم: ${money(ex)}</p>`} function reportMonth(){const a=monthSales(),t=a.reduce((x,s)=>x+s.total,0);reportBox.innerHTML=`<div class="kpi">${money(t)}</div><p>عدد الفواتير هذا الشهر: ${a.length}</p>`} function reportAll(){const t=sales.reduce((x,s)=>x+s.total,0);reportBox.innerHTML=`<div class="kpi">${money(t)}</div><p>عدد الفواتير: ${sales.length}</p>`} function reportProfit(){const revenue=sales.reduce((a,s)=>a+s.total,0),cost=sales.reduce((a,s)=>a+s.items.reduce((z,i)=>z+(i.buy||0)*i.qty,0),0),ex=expenses.reduce((a,e)=>a+e.amount,0);reportBox.innerHTML=`<p>رقم المبيعات: <b>${money(revenue)}</b></p><p>تكلفة السلع المباعة: <b>${money(cost)}</b></p><p>المصاريف: <b>${money(ex)}</b></p><div class="kpi">الربح التقريبي: ${money(revenue-cost-ex)}</div>`}
function renderDashboard(){statProducts.textContent=products.length;statStock.textContent=money(products.reduce((a,p)=>a+p.qty*p.buy,0));statSales.textContent=money(daySales().reduce((a,s)=>a+s.total,0));statLow.textContent=products.filter(p=>p.qty<=p.min).length;todaySummary.innerHTML=`<p>الفواتير: <b>${daySales().length}</b></p><p>المبيعات: <b>${money(daySales().reduce((a,s)=>a+s.total,0))}</b></p>`;const low=products.filter(p=>p.qty<=p.min).slice(0,8);lowList.innerHTML=low.length?low.map(p=>`<p class="dangerText">${esc(p.ar)} — ${p.qty}</p>`).join(''):'<p class="okText">لا يوجد نقص مهم.</p>'}
function backup(){const data={version:2,date:new Date().toISOString(),products,sales,purchases,suppliers,expenses};const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download='doukan_al_hay_backup.json';a.click()} function restore(input){const f=input.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const d=JSON.parse(r.result);products=Array.isArray(d.products)?d.products:products;sales=Array.isArray(d.sales)?d.sales:sales;purchases=Array.isArray(d.purchases)?d.purchases:purchases;suppliers=Array.isArray(d.suppliers)?d.suppliers:suppliers;expenses=Array.isArray(d.expenses)?d.expenses:expenses;save();renderAll();alert('تم الاسترجاع بنجاح')}catch{alert('ملف غير صالح')}};r.readAsText(f)} function exportCSV(){const rows=[['barcode','name_ar','name_fr','category','purchase_price','sale_price','quantity'],...products.map(p=>[p.barcode,p.ar,p.fr,p.cat,p.buy,p.sell,p.qty])];const csv=rows.map(r=>r.map(x=>`"${String(x??'').replaceAll('"','""')}"`).join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download='doukan_products.csv';a.click()} function resetAll(){if(confirm('سيتم حذف المنتجات والمبيعات والمشتريات والموردين والمصاريف نهائياً. هل أنت متأكد؟')){Object.values(K).forEach(k=>localStorage.removeItem(k));products=[];sales=[];purchases=[];suppliers=[];expenses=[];cart=[];renderAll()}}
function renderAll(){renderProducts();renderCart();renderPurchases();renderSuppliers();renderExpenses();renderDashboard()} renderAll();
